### PR TITLE
Create less need to duplicate code when adding and removing localStorage

### PR DESCRIPTION
**Pull request by hkd987**
This should allow a cleaner way to set and remove items from localStorage.

### CODE REVIEW

**Comment by hkd987** [comment]
@rcastera can I get a review on this when you have time since it modifies a section of your code

**Comment by hkd987** [comment]
@nidkil can you provide a better example of the proccessStoagekeys function that your looking for im not following along.

**Comment by nidkil** [comment]
Hi,

Something like this...

```
_setStorage (authResult, profile = null) {
    const processFunc = (value, profile) => {
        if (profile) {
            const setValue = value.authKey ? value.authKey : value.profileKey
            localStorage.setItem(`gapi.${value.name}`, setValue)
        }
    }
    processStorageKeys(processFunc, authResult, profile)
}

_clearStorage () {
    const processFunc = (value) => {
        localStorage.removeItem(`gapi.${value.name}`)
    }
    processStorageKeys(processFunc)
}
````

and ...

````
export const storageProcessor = (processFunc, authResult = null, profile = null) => {
    if (!processFunc) {
        throw Error('processFunc must be provided')
    }

    const storageKeys = getStorageKeys(authResult, profile)

    storageKeys.forEach((value) => processFunc(value, profile))
}
```

You might have to bind the processFunc to have the right context, like this `processFunc.bind(this)`.

Does this help?

**Comment by cedpoilly** [comment]
Repo requires clean up first.

**Pull request closed without merging**
